apiVersion: v1
kind: Namespace
metadata:
  name: cvbdfgghbfd-prod
  labels:
    environment-id: env_6e4a10c5-3c11-4337-85a8-dc0bfbd74fb9
    project-id: project_1e1aba07-bc73-4869-a6c5-a6a15ac87ede
    project-name: cvbdfgghbfd
    environment-name: prod
    organization-id: org_9aad87d0-abbc-48f9-9038-002316f0475a
